const cricketCommentary = [
  "Welcome to the India vs Australia Test match at the MCG!",
  "The pitch looks good for batting with some early moisture",
  "India wins the toss and elects to bat first",
  "Rohit Sharma and Shubman Gill walk out to open the innings",
  "Pat Cummins will bowl the first over",
  "FOUR! Rohit gets off the mark with a beautiful cover drive",
  "Good length delivery, defended back to the bowler",
  "Short ball! Rohit ducks under it comfortably",
  "Edge taken! But it falls short of the slip fielder",
  "That's a maiden over from Cummins, excellent start",
  "Mitchell Starc comes into the attack now",
  "Wide delivery, Gill lets it go to the keeper",
  "SIX! What a shot! Gill pulls it over square leg for maximum",
  "The crowd is on its feet! Spectacular batting",
  "Bouncer! Gill sways away from the line",
  "Thick edge but safe! Goes through the gap in slips",
  "50 partnership comes up between the openers",
  "Brilliant fielding by Smith, saves a certain boundary",
  "WICKET! Rohit edges behind, caught by Carey for 23",
  "Virat Kohli makes his way to the crease",
  "The crowd erupts as King Kohli takes guard",
  "First ball faced, Kohli defends it solidly",
  "Nathan Lyon introduced into the attack",
  "Flighted delivery, Gill drives it through covers",
  "Appeal for LBW! Umpire says not out",
  "Australia reviews the decision immediately",
  "Ball tracking shows it was missing leg stump",
  "Review lost! Australia down to one review",
  "FOUR! Kohli finds the gap, classic wrist work",
  "Century partnership! Excellent batting display",
  "Drinks break called, players hydrating",
  "Temperature is soaring at 35 degrees Celsius",
  "Play resumes, Lyon continues his spell",
  "STUMPED! Gill dances down but misses completely",
  "Brilliant glovework by Carey behind the stumps",
  "Gill departs for a well-made 67",
  "KL Rahul comes to the crease at number 4",
  "Pressure on India now, two quick wickets",
  "Short leg in place for the new batsman",
  "Rahul gets off the mark with a gentle push",
  "FOUR! Kohli cuts it fine past the slip cordon",
  "150 up for India, but at the cost of 3 wickets",
  "Cameron Green brought into the attack",
  "Extra bounce from Green, Kohli adjusts well",
  "WICKET! Kohli holes out to mid-on for 45",
  "Big wicket for Australia! The crowd falls silent",
  "Rishabh Pant walks in with his typical swagger",
  "Pant immediately looks to take on the bowling",
  "SIX! First ball six! Pant smashes it over long-on",
  "Audacious shot! Only Pant could play that",
  "The momentum shifts back to India",
  "Rahul playing the anchor role perfectly",
  "FOUR! Reverse sweep from Pant, innovation at its best",
  "200 up for India! Excellent recovery",
  "Tea break called, fascinating session of cricket",
  "Australia will be happy with 4 wickets",
  "India 203/4 at tea, Rahul 34* Pant 28*",
];

module.exports = {
  cricketCommentary,
};
